### ISSUE TITLE
UI Test error.

### ISSUE THREAD

**Issue by ronycohen** [thechane/consul#2]
Hello !

thank you for your share !
I encounter an error with your file.

I have 4 nodes in my docker swarm : 

![image](https://user-images.githubusercontent.com/7273443/29969352-fd259906-8f1f-11e7-9cec-6eaf148c41b3.png)

I launched your file.

![image](https://user-images.githubusercontent.com/7273443/29969462-83252b5c-8f20-11e7-81c9-dd41feb3cd9d.png)

The seed container is properly created, and then I have 4 services of testconsul_cluster.

![image](https://user-images.githubusercontent.com/7273443/29969488-a2837170-8f20-11e7-9d2c-62197be359a9.png)

I encounter an error when trying to connect to the UI (of each clusters).
![image](https://user-images.githubusercontent.com/7273443/29969536-d5a00c94-8f20-11e7-9367-177d68696d35.png)

Did I make any mistake ?
Thank you.

**Comment by ronycohen** [comment]
OK I got the errors : 

![image](https://user-images.githubusercontent.com/7273443/29970161-c5c0e0e8-8f23-11e7-9633-36d81fc75877.png)

**Comment by thechane** [comment]
Did you label your docker nodes and make sure there was no overlap with the seed and cluster nodes?
To label each node see - https://docs.docker.com/engine/reference/commandline/node_update/

... in my example I used access=consul_seed as the label for one node that would take the seed service. The cluster service was then told to avoid using nodes with this label.

**Comment by ronycohen** [comment]
Thank you very much for your answer, I'm on it.

**Comment by Blaiserman** [comment]
The compose file use engine.labels.access but it must be node.labels.access. After this change working fine.
